#!/bin/sh

PATH=$PATH:$HOME:$HOME/bin:$HOME/sources/dotfiles/scripts/

source /etc/X11/xinit/xinitrc.d/30-dbus
eval $(/usr/bin/gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh)
export GNOME_KEYRING_CONTROL GNOME_KEYRING_PID GPG_AGENT_INFO SSH_AUTH_SOCK

xset s off                                  &
xset -dpms                                  &
xrdb -merge ~/.Xresources                   &
autocutsel -fork                            &
autocutsel -fork -selection PRIMARY         &
pulseaudio --start                          &
dunst                                       &
irexec                                      &
pasystray                                   &
skype                                       &
qtox                                        &
dropboxd                                    &
transmission-qt                             &
xmodmap ~/.keybindings                      &
redshift-gtk                                &

i3
