#!/bin/sh
export TERMINAL=sakura
export GOPATH=$HOME/go
PATH=$PATH:$HOME:$HOME/bin:$HOME/sources/dotfiles/scripts/:$GOPATH/bin
source /etc/X11/xinit/xinitrc.d/30-dbus
eval $(/usr/bin/gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh)
export GNOME_KEYRING_CONTROL GNOME_KEYRING_PID GPG_AGENT_INFO SSH_AUTH_SOCK
exec pulseaudio --start &
exec dunst &
exec xcompmgr &
exec irexec &
exec pasystray &
exec i3
