#!/bin/sh
export TERMINAL=sakura
export GOPATH=$HOME/go
PATH=$PATH:$HOME:$HOME/bin:$HOME/sources/dotfiles/scripts/:$GOPATH/bin
source /etc/X11/xinit/xinitrc.d/30-dbus
eval $(/usr/bin/gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh)
export GNOME_KEYRING_CONTROL GNOME_KEYRING_PID GPG_AGENT_INFO SSH_AUTH_SOCK
exec xrdb -merge ~/.Xresources &
exec autocutsel -fork &
exec autocutsel -selection PRIMARY -fork &
exec pulseaudio --start &
exec dunst &
exec compton &
exec irexec &
exec pasystray &
exec xflux -z 80920 &
exec ibus-daemon --xim &
exec xmodmap ~/.keybindings &
exec i3
