#!/usr/bin/fish
function info
    echo -n $argv
    echo -n " | "
end
while true
    info (basename (mocp -i | grep File | sed -re "s/.*: (.*)\$/\1/") | sed -r "s/(\.flac|\.mp3)//")
    info "home:" (df -l | sed -nr "s/\/dev\/sda2.*([0-9]{2}%).*/\1/p")
    info "sda1:" (df -l | sed -nr "s/\/dev\/sda1.*([0-9]{2}%).*/\1/p")
    echo -n (date +"%Y-%m-%d %l:%M %p")
    sleep 5
    echo -ne "\n"
end
