#!/usr/bin/fish
set line ""
function info
    set line $line $argv
    set line $line "|"
end
while true
    info (basename (mocp -i | grep File | sed -re "s/.*: (.*)\$/\1/") | sed -r "s/(\.flac|\.mp3)//")
    info "home:" (df -l | sed -nr "s/\/dev\/sda2.*([0-9]{2}%).*/\1/p")
    info "sda1:" (df -l | sed -nr "s/\/dev\/sda1.*([0-9]{2}%).*/\1/p")
    set line $line (date +"%Y-%m-%d %l:%M %p")

    echo $line
    sleep 5
    set line ""
end
