#!/bin/bash
if [[ $1 == *.torrent ]]
then
  notify-send "Added $(basename "$1") to rTorrent"
  mv "$1" ~/torrents/
fi
if [[ $1 == magnet:* ]]
then
  notify-send "Added magnet link to rTorrent"
  
  xmlrpc rtorrent load_start "$(echo "$1" | sed -re "s/:/\\\\:/g")"
fi
