#!/bin/bash
if [[ $1 == *.torrent ]]
then
  notify-send "Added $(basename "$1") to Transmission"
  mv "$1" ~/torrents/
fi
if [[ $1 == magnet:* ]]
then
  notify-send "Added magnet link to Transmission"
  
  transmission-qt "$1"
fi
