#!/bin/sh
set -e
escrotum -s /tmp/scrot.png;
json=$(curl -F "files[]"=@/tmp/scrot.png https://pomf.se/upload.php)
path=$( echo "$json" | jq -r .files[0].url)
echo -n https://a.pomf.se/$path | xclip -sel clip
notify-send "Upload complete:\nhttps://a.pomf.se/$path"
xdg-open https://a.pomf.se/$path
