#!/bin/sh
# Usage: ./video2gif input-file resolution output-file.gif

if [ $# -ne 5 ]
then
    echo "Usage: video2gif input-file output-file.gif resolution start-time duration"
    echo "Example: video2gif supercoolvideo.mkv output.gif 640:480 00:15:30 00:00:10"
    exit 1
fi

# Check for required software
for dep in convert ffmpeg gifsicle
do command -v $dep >/dev/null 2>&1 || { echo >&2 "This script requires ffmpeg, gifsicle, and convert."; exit 1; }
done

# Make temporary directory and extract frames into it
tempdir=$(mktemp -d)
ffmpeg -loglevel panic -ss $4 -i "$1" -vf scale=$3 -t $5 -r 10 $tempdir/output%02d.png

for file in $tempdir/*.png; do convert $file $file.gif; done

gifsicle --no-warnings --optimize --delay 10 --loop $tempdir/*.gif > "$2"

rm -r $tempdir
