#!/bin/bash
cookies_dir="$(mktemp -d /tmp/youtube-dl_mpv.XXXX)"
cookies_file="${cookies_dir}/cookies"
user_agent="$(youtube-dl --dump-user-agent)"
fifo=$(mktemp -u)
mkfifo $fifo
first=0

youtube-dl --user-agent="$user_agent" \
    --cookies="$cookies_file" \
    --netrc \
    --get-url \
    --ignore-errors \
    "$1" | while read url; do
    if [[ $first == 0 ]]
    then
        mpv --idle \
            --input-file $fifo \
            --no-consolecontrols \
            --cookies \
            --cookies-file="$cookies_file" \
            --user-agent="$user_agent" \
            "$url" &
        first=1
    else
        echo "loadfile \"$url\" append" > $fifo
    fi
done

rm $fifo
rm -rf "$cookies_dir"
